// Bookings — hotels + transport (flights, trains, cars, ferries)

window.BOOKINGS = {
  hotels: [
    {
      id: "ho1",
      name: "Park Hotel Tokyo",
      address: "1-7-1 Higashi-Shimbashi, Minato, Tokyo",
      checkIn: { date: "Apr 12, 2026", time: "3:00 PM" },
      checkOut: { date: "Apr 13, 2026", time: "11:00 AM" },
      nights: 1,
      room: "King · Artist Floor 31F",
      guests: 2,
      ref: "PHT-29481",
      cost: { amount: 380, currency: "USD" },
      cancellation: "Free until Apr 10",
      contact: "+81 3-6252-1111",
      notes: "Late check-in available. Request high floor.",
      attachment: { name: "Park_Hotel_voucher.pdf", size: "184 KB" },
      thumb: "#dcd0ff",
      dayIdx: 0,
    },
    {
      id: "ho2",
      name: "Hoshinoya Fuji",
      address: "1408 Oishi, Fujikawaguchiko, Yamanashi",
      checkIn: { date: "Apr 13, 2026", time: "3:00 PM" },
      checkOut: { date: "Apr 14, 2026", time: "12:00 PM" },
      nights: 1,
      room: "Cabin Suite · Lake-facing",
      guests: 2,
      ref: "HFY-77231",
      cost: { amount: 720, currency: "USD" },
      cancellation: "Free until Apr 11",
      contact: "+81 50-3134-8091",
      notes: "Glamping resort. Dinner included.",
      attachment: { name: "Hoshinoya_confirmation.pdf", size: "212 KB" },
      thumb: "#cde8c4",
      dayIdx: 1,
    },
    {
      id: "ho3",
      name: "Hakone Yumoto Onsen Tenseien",
      address: "682 Yumoto, Hakone, Kanagawa",
      checkIn: { date: "Apr 14, 2026", time: "3:00 PM" },
      checkOut: { date: "Apr 15, 2026", time: "10:00 AM" },
      nights: 1,
      room: "Japanese Suite w/ private onsen",
      guests: 2,
      ref: "TSN-9920",
      cost: { amount: 540, currency: "USD" },
      cancellation: "Non-refundable",
      contact: "+81 460-85-5555",
      notes: "Kaiseki dinner at 7pm. Yukata provided.",
      attachment: { name: "Tenseien_eVoucher.pdf", size: "156 KB" },
      thumb: "#cdd9e8",
      dayIdx: 2,
    },
    {
      id: "ho4",
      name: "Park Hotel Tokyo",
      address: "1-7-1 Higashi-Shimbashi, Minato, Tokyo",
      checkIn: { date: "Apr 15, 2026", time: "3:00 PM" },
      checkOut: { date: "Apr 16, 2026", time: "11:00 AM" },
      nights: 1,
      room: "King · Artist Floor 31F",
      guests: 2,
      ref: "PHT-29482",
      cost: { amount: 380, currency: "USD" },
      cancellation: "Free until Apr 13",
      contact: "+81 3-6252-1111",
      notes: "Same room as Day 1. Final night.",
      attachment: { name: "Park_Hotel_voucher_2.pdf", size: "184 KB" },
      thumb: "#dcd0ff",
      dayIdx: 3,
    },
  ],
  transport: [
    {
      id: "tr1",
      type: "flight",
      title: "JL5 · Los Angeles → Tokyo",
      provider: "Japan Airlines",
      ref: "JL-LAX-NRT-7821",
      from: { code: "LAX", name: "Los Angeles Intl", time: "11:45 AM", date: "Apr 11, 2026", terminal: "B" },
      to: { code: "NRT", name: "Narita Intl", time: "3:50 PM", date: "Apr 12, 2026", terminal: "1" },
      duration: "11h 35m",
      seats: "14A, 14B · Economy",
      bag: "2 × 23kg checked",
      cost: { amount: 2480, currency: "USD" },
      attachment: { name: "JL5_eTicket.pdf", size: "92 KB" },
      dayIdx: 0,
    },
    {
      id: "tr2",
      type: "train",
      title: "Shinkansen · Tokyo → Odawara",
      provider: "JR East",
      ref: "JR-TKY-ODW-440",
      from: { code: "TKY", name: "Tokyo Sta.", time: "9:15 AM", date: "Apr 14, 2026", terminal: "Track 14" },
      to: { code: "ODW", name: "Odawara Sta.", time: "9:51 AM", date: "Apr 14, 2026", terminal: "Track 11" },
      duration: "36m",
      seats: "Car 7 · 12A, 12B · Reserved",
      bag: "Carry-on",
      cost: { amount: 76, currency: "USD" },
      attachment: { name: "JR_Pass_voucher.pdf", size: "45 KB" },
      dayIdx: 2,
    },
    {
      id: "tr3",
      type: "car",
      title: "Toyota Prius · 3-day rental",
      provider: "Times Car Rental",
      ref: "TCR-FUJI-2204",
      from: { code: "FUJI", name: "Kawaguchiko Sta.", time: "10:00 AM", date: "Apr 13, 2026", terminal: "Pickup B" },
      to: { code: "FUJI", name: "Kawaguchiko Sta.", time: "9:00 AM", date: "Apr 14, 2026", terminal: "Return" },
      duration: "1 day",
      seats: "Compact · Hybrid · ETC card",
      bag: "—",
      cost: { amount: 88, currency: "USD" },
      attachment: { name: "Times_rental_agreement.pdf", size: "112 KB" },
      dayIdx: 1,
    },
    {
      id: "tr4",
      type: "flight",
      title: "JL62 · Tokyo → Los Angeles",
      provider: "Japan Airlines",
      ref: "JL-NRT-LAX-7821",
      from: { code: "NRT", name: "Narita Intl", time: "4:20 PM", date: "Apr 16, 2026", terminal: "1" },
      to: { code: "LAX", name: "Los Angeles Intl", time: "10:45 AM", date: "Apr 16, 2026", terminal: "B" },
      duration: "10h 25m",
      seats: "22F, 22G · Economy",
      bag: "2 × 23kg checked",
      cost: { amount: 2480, currency: "USD" },
      attachment: { name: "JL62_eTicket.pdf", size: "94 KB" },
      dayIdx: 4,
    },
  ],
};
