// Mockup-trip seed data. Mirrors design/data.js TRIP shape so we can
// drop the example "Mount Fuji & Kamakura" trip into a fresh user's
// account for evaluation.
//
// Phase 2A only — Phase 2B+ ships real trip create / list flows.

import type { NewDay, NewPlace, NewSegment } from '@/db/schema';

export type SeedDay = Omit<NewDay, 'id' | 'tripId'> & {
  places: Array<Omit<NewPlace, 'id' | 'dayId'>>;
  segments: Array<Omit<NewSegment, 'id' | 'dayId'>>;
};

export const SEED_TRIP = {
  title: 'Mount Fuji & Kamakura',
  subtitle: 'Tokyo · Hakone · Kamakura',
  startDate: '2026-04-12',
  endDate: '2026-04-16',
  cover: 'fuji',
  collaborators: [
    { initials: 'AY', color: '#0071e3' },
    { initials: 'MK', color: '#5b3fd9' },
    { initials: 'TS', color: '#29a847' },
  ],
  recco: [
    { name: 'Fuji-Q Highland', sub: 'Theme park · 12 km', color: '#ffd6a5' },
    { name: 'Iyashi no Sato', sub: 'Heritage village · 8 km', color: '#a5d8ff' },
    { name: 'Aokigahara Forest', sub: 'Hiking · 14 km', color: '#b2f2bb' },
    { name: 'Saiko Bat Cave', sub: 'Cave tour · 11 km', color: '#d0bfff' },
  ],
  days: [
    {
      idx: 0,
      label: 'Sat',
      num: 12,
      date: 'Saturday, April 12',
      title: 'Arrival in Tokyo',
      summaryDistance: '8.4 km',
      summaryTime: '1h 12m',
      optimizeSavingsTime: null,
      optimizeSavingsSwap: null,
      places: [
        {
          idx: 0,
          kind: 'hotel',
          name: 'Park Hotel Tokyo',
          category: 'Hotel · Check-in',
          rating: 4.6,
          reviews: 2147,
          time: '3:00 PM',
          duration: 'Check-in',
          price: '$$$',
          address: '1-7-1 Higashi-Shimbashi, Minato, Tokyo',
          phone: '+81 3-6252-1111',
          website: 'parkhoteltokyo.com',
          hours: 'Front desk · 24h',
          tags: ['Boutique', 'Skyline view', 'Free Wi-Fi'],
          thumb: '#dcd0ff',
          note: 'Confirmation #PHT-29481. Late check-in available.',
          bookingRef: 'PHT-29481',
          bookingRoom: 'King · Artist Floor 31F',
          bookingNights: 4,
          bookingTotal: '$1,240',
          x: 612,
          y: 412,
        },
        {
          idx: 1,
          kind: 'food',
          name: 'Tsuta Ramen',
          category: 'Michelin · Ramen',
          rating: 4.7,
          reviews: 3210,
          time: '7:30 PM',
          duration: '1h',
          price: '$$',
          address: 'Sugamo 1-14-1, Toshima, Tokyo',
          phone: '+81 3-3943-1007',
          hours: 'Today · 11:00 – 21:00',
          tags: ['Michelin Bib', 'Truffle shoyu', 'Cash only'],
          thumb: '#ffd0a8',
          note: 'Arrive 30m early — line forms fast.',
          x: 654,
          y: 388,
        },
        {
          idx: 2,
          kind: 'sight',
          name: 'Tokyo Tower Observation',
          category: 'Landmark · 30m',
          rating: 4.5,
          reviews: 18402,
          time: '9:00 PM',
          duration: '30m',
          price: '$',
          address: '4 Chome-2-8 Shibakoen, Minato, Tokyo',
          phone: '+81 3-3433-5111',
          hours: 'Today · 09:00 – 23:00',
          tags: ['Night view', 'Photo spot'],
          thumb: '#ffb8b8',
          x: 595,
          y: 425,
        },
      ],
      segments: [
        { idx: 0, mode: 'drive', distance: '4.2 km', time: '14m' },
        { idx: 1, mode: 'walk', distance: '1.1 km', time: '12m' },
      ],
    },
    {
      idx: 1,
      label: 'Sun',
      num: 13,
      date: 'Sunday, April 13',
      title: 'Mount Fuji & Lake Kawaguchi',
      summaryDistance: '184 km',
      summaryTime: '3h 40m',
      optimizeSavingsTime: '47m',
      optimizeSavingsSwap: '2 stops',
      places: [
        {
          idx: 0, kind: 'sight', name: 'Chureito Pagoda',
          category: 'Viewpoint · 1h 30m', rating: 4.8, reviews: 12483,
          time: '8:30 AM', duration: '1h 30m', price: 'Free',
          address: 'Asakawa 3353-1, Fujiyoshida, Yamanashi',
          hours: 'Open 24h · Pagoda 09:00 – 16:00',
          tags: ['Sunrise', '398 steps', 'Cherry blossoms'],
          thumb: '#ffd5dc',
          note: 'Best photo spot before 10am — light hits the pagoda.',
          x: 268, y: 312,
        },
        {
          idx: 1, kind: 'sight', name: 'Oishi Park',
          category: 'Park · 1h', rating: 4.7, reviews: 5621,
          time: '11:00 AM', duration: '1h', price: 'Free',
          address: 'Oishi 2585-1, Fujikawaguchiko, Yamanashi',
          hours: 'Open 24h',
          tags: ['Lake view', 'Lavender (summer)'],
          thumb: '#cde8c4', x: 332, y: 286,
        },
        {
          idx: 2, kind: 'food', name: 'Hoto Fudo Kawaguchiko',
          category: 'Hoto noodles · Lunch', rating: 4.6, reviews: 4218,
          time: '12:45 PM', duration: '1h 15m', price: '$$',
          address: '707 Funatsu, Fujikawaguchiko',
          phone: '+81 555-72-8511',
          hours: 'Today · 11:00 – 19:00',
          tags: ['Local specialty', 'Vegetarian options'],
          thumb: '#ffe0a8', x: 358, y: 308,
        },
        {
          idx: 3, kind: 'sight', name: 'Arakurayama Sengen Park',
          category: 'Cherry blossoms · 2h', rating: 4.9, reviews: 9874,
          time: '2:30 PM', duration: '2h', price: 'Free',
          address: 'Arakura, Fujiyoshida', hours: 'Open 24h',
          tags: ['Iconic view', 'Sakura peak Apr 10–20'],
          thumb: '#fcc7d4', x: 282, y: 348,
        },
        {
          idx: 4, kind: 'sight', name: 'Lake Kawaguchi Cruise',
          category: 'Boat tour · 30m', rating: 4.4, reviews: 1893,
          time: '4:30 PM', duration: '30m', price: '$',
          address: 'Funatsu 4034, Fujikawaguchiko',
          hours: 'Today · 09:00 – 16:30 · last boat 16:30',
          tags: ['Family-friendly', 'Indoor'],
          thumb: '#bcd9f0',
          bookingRef: 'KWG-7723', bookingRoom: '2 adults',
          bookingTotal: '¥2,000', x: 348, y: 264,
        },
        {
          idx: 5, kind: 'food', name: 'Fujizakura Country Club',
          category: 'Sunset dinner', rating: 4.5, reviews: 612,
          time: '6:30 PM', duration: '2h', price: '$$$',
          address: 'Funatsu 6713, Fujikawaguchiko',
          phone: '+81 555-73-1111',
          hours: 'Today · 17:30 – 22:00',
          tags: ['Reservation only', 'Mountain view'],
          thumb: '#e6d5b0', x: 296, y: 232,
        },
      ],
      segments: [
        { idx: 0, mode: 'drive', distance: '8.1 km', time: '18m' },
        { idx: 1, mode: 'drive', distance: '2.4 km', time: '9m' },
        { idx: 2, mode: 'drive', distance: '11.6 km', time: '24m' },
        { idx: 3, mode: 'drive', distance: '9.7 km', time: '22m' },
        { idx: 4, mode: 'drive', distance: '14.2 km', time: '30m' },
      ],
    },
    {
      idx: 2,
      label: 'Mon', num: 14, date: 'Monday, April 14',
      title: 'Hakone Onsen Day',
      summaryDistance: '62 km', summaryTime: '2h 10m',
      optimizeSavingsTime: null, optimizeSavingsSwap: null,
      places: [
        {
          idx: 0, kind: 'sight', name: 'Hakone Open-Air Museum',
          category: 'Sculpture park · 2h', rating: 4.7, reviews: 8432,
          time: '10:00 AM', duration: '2h', price: '$$',
          address: 'Ninotaira 1121, Hakone',
          phone: '+81 460-82-1161',
          hours: 'Today · 09:00 – 17:00',
          tags: ['Picasso pavilion', 'Foot bath', 'Outdoor'],
          thumb: '#cdd9e8', x: 445, y: 462,
        },
        {
          idx: 1, kind: 'sight', name: 'Hakone Ropeway',
          category: 'Cable car · 40m', rating: 4.6, reviews: 6781,
          time: '1:00 PM', duration: '40m', price: '$$',
          address: 'Sounzan Sta., Hakone',
          hours: 'Today · 09:00 – 17:00',
          tags: ['Owakudani views', 'Volcanic vents'],
          thumb: '#d4c0e8',
          note: 'Skip if winds > 15 m/s — it closes.',
          x: 478, y: 438,
        },
        {
          idx: 2, kind: 'food', name: 'Itoh Dining Hakone',
          category: 'Wagyu · Dinner', rating: 4.8, reviews: 1244,
          time: '7:00 PM', duration: '2h', price: '$$$$',
          address: 'Gora 1300-64, Hakone',
          phone: '+81 460-83-8209',
          hours: 'Today · 17:30 – 22:00',
          tags: ['Teppanyaki', 'Counter seating'],
          thumb: '#e8c0c0',
          note: 'Reserved · 7pm · party of 2',
          bookingRef: 'ITH-4421', bookingRoom: 'Counter · 2 guests',
          bookingTotal: '¥38,000', x: 462, y: 482,
        },
      ],
      segments: [
        { idx: 0, mode: 'drive', distance: '3.8 km', time: '11m' },
        { idx: 1, mode: 'drive', distance: '5.2 km', time: '14m' },
      ],
    },
    {
      idx: 3,
      label: 'Tue', num: 15, date: 'Tuesday, April 15',
      title: 'Kamakura Temples',
      summaryDistance: '11.3 km', summaryTime: '1h 45m',
      optimizeSavingsTime: null, optimizeSavingsSwap: null,
      places: [
        {
          idx: 0, kind: 'sight', name: 'Tsurugaoka Hachimangu',
          category: 'Shrine · 1h', rating: 4.6, reviews: 11200,
          time: '9:30 AM', duration: '1h', price: 'Free',
          address: '2-1-31 Yukinoshita, Kamakura',
          hours: 'Today · 06:00 – 20:30',
          tags: ['Main shrine', 'Lotus pond'],
          thumb: '#ffd5b4', x: 718, y: 478,
        },
        {
          idx: 1, kind: 'sight', name: 'Kotoku-in (Great Buddha)',
          category: 'Temple · 45m', rating: 4.7, reviews: 24109,
          time: '11:30 AM', duration: '45m', price: '$',
          address: '4-2-28 Hase, Kamakura',
          phone: '+81 467-22-0703',
          hours: 'Today · 08:00 – 17:30',
          tags: ['Daibutsu', 'Iconic'],
          thumb: '#c8d8c0', x: 690, y: 502,
        },
        {
          idx: 2, kind: 'food', name: 'Bowls Donburi Cafe',
          category: 'Lunch · 45m', rating: 4.5, reviews: 1820,
          time: '1:00 PM', duration: '45m', price: '$$',
          address: '2-14-7 Hase, Kamakura',
          hours: 'Today · 11:00 – 16:00',
          tags: ['Donburi', 'Quick'],
          thumb: '#fce0bf', x: 706, y: 488,
        },
        {
          idx: 3, kind: 'sight', name: 'Hasedera Temple',
          category: 'Temple · 1h', rating: 4.8, reviews: 9012,
          time: '2:30 PM', duration: '1h', price: '$',
          address: '3-11-2 Hase, Kamakura',
          phone: '+81 467-22-6300',
          hours: 'Today · 08:00 – 17:00',
          tags: ['Sea view', 'Garden'],
          thumb: '#d0e4d0', x: 684, y: 514,
        },
      ],
      segments: [
        { idx: 0, mode: 'drive', distance: '1.8 km', time: '8m' },
        { idx: 1, mode: 'walk', distance: '0.4 km', time: '5m' },
        { idx: 2, mode: 'walk', distance: '0.9 km', time: '11m' },
      ],
    },
    {
      idx: 4,
      label: 'Wed', num: 16, date: 'Wednesday, April 16',
      title: 'Tokyo · Departure',
      summaryDistance: '22 km', summaryTime: '1h 30m',
      optimizeSavingsTime: null, optimizeSavingsSwap: null,
      places: [
        {
          idx: 0, kind: 'food', name: 'Tsukiji Outer Market',
          category: 'Breakfast · 1h', rating: 4.6, reviews: 32108,
          time: '8:00 AM', duration: '1h', price: '$$',
          address: '4 Chome Tsukiji, Chuo, Tokyo',
          hours: 'Today · 05:00 – 14:00',
          tags: ['Street food', 'Fresh sushi'],
          thumb: '#ffd0c8', x: 626, y: 408,
        },
        {
          idx: 1, kind: 'sight', name: 'Imperial Palace Gardens',
          category: 'Walk · 1h', rating: 4.5, reviews: 8910,
          time: '10:00 AM', duration: '1h', price: 'Free',
          address: '1-1 Chiyoda, Chiyoda, Tokyo',
          hours: 'Today · 09:00 – 17:00',
          tags: ['Closed Mon/Fri'],
          thumb: '#c8e0c8', x: 612, y: 396,
        },
        {
          idx: 2, kind: 'transit', name: 'Narita Airport (NRT)',
          category: 'Departure · 4:20 PM',
          rating: null, reviews: null,
          time: '1:00 PM', duration: 'Flight check-in', price: null,
          address: 'Narita International Airport, Chiba',
          tags: ['Terminal 1', 'Flight JL5', '16:20'],
          thumb: '#d0d4dc',
          bookingRef: 'JL5-NRT-LAX', bookingRoom: '2 seats · Economy',
          bookingTotal: 'Confirmed', x: 712, y: 372,
        },
      ],
      segments: [
        { idx: 0, mode: 'walk', distance: '1.2 km', time: '14m' },
        { idx: 1, mode: 'drive', distance: '65 km', time: '1h 10m' },
      ],
    },
  ] as SeedDay[],
};
